### ISSUE TITLE
Whoops! Cannot reach System Daemon. (Noob)

### ISSUE THREAD

**Issue by Hitmanjammer** [bubuntux/nordvpn#133]
Hello,

I'm very new do all this and seem to have come across an error and have no real way to troubleshoot due to limited knowledge.

Hopefully it's decently easy fix 

This is the command I ran:
docker run -ti --cap-add=NET_ADMIN --cap-add=SYS_MODULE --device /dev/net/tun --name vpn \
            --sysctl net.ipv4.conf.all.rp_filter=2 \
            -e USER=****** -e PASS='****' \
            -e CONNECT=***** -e TECHNOLOGY=NordLynx -d bubuntux/nordvpn:3.7.4

And the error I got: 

```/usr/local/go/src/net/fd_unix.go:238 +0x42
,net.(*UnixListener).accept(0xc0002020c0, 0x40e928, 0xc00022a000, 0xc00022a088)
,	/usr/local/go/src/net/unixsock_posix.go:162 +0x32
,net.(*UnixListener).Accept(0xc0002020c0, 0xc0002d15f0, 0xc000080e90, 0xc00022a088, 0x4b4225)
,	/usr/local/go/src/net/unixsock.go:260 +0x64
,google.golang.org/grpc.(*Server).Serve(0xc000102c00, 0xc9aba0, 0xc0002020c0, 0x0, 0x0)
,	/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:597 +0x210
,main.main.func2(0xc000102c00)
,	/builds/nordvpn/apps-source/linux-app/src/cmd/daemon/main.go:136 +0xd8
,created by main.main
,	/builds/nordvpn/apps-source/linux-app/src/cmd/daemon/main.go:111 +0x941
,
,goroutine 24 [chan receive]:
,nordvpn/daemon.IPSetUpdate(0xc0001328a0, 0xca0320, 0xc7f000)
,	/builds/nordvpn/apps-source/linux-app/src/daemon/job_killswitch.go:12 +0x52
,created by main.main
,	/builds/nordvpn/apps-source/linux-app/src/cmd/daemon/main.go:145 +0x9f9
,
,goroutine 25 [runnable]:
,encoding/gob.(*decoderState).decodeUint(0xc00000e6a0, 0xc00000e6a0)
,	/usr/local/go/src/encoding/gob/decode.go:150 +0x309
,encoding/gob.(*Decoder).decodeStruct(0xc0001aa380, 0xc00000f080, 0xb01fa0, 0xc0000c63f0, 0x199)
,	/usr/local/go/src/encoding/gob/decode.go:450 +0x111
,encoding/gob.(*Decoder).decOpFor.func4(0xc0003b16c0, 0xc00000e680, 0xb01fa0, 0xc0000c63f0, 0x199)
,	/usr/local/go/src/encoding/gob/decode.go:860 +0x54
,encoding/gob.(*Decoder).decodeArrayHelper(0xc0001aa380, 0xc00000e680, 0xa77e80, 0xc0009b34c8, 0x197, 0xc00000f180, 0x6, 0xc8e1a0, 0xc000113e50, 0x0)
,	/usr/local/go/src/encoding/gob/decode.go:530 +0x17b
,encoding/gob.(*Decoder).decodeSlice(0xc0001aa380, 0xc00000e680, 0xa77e80, 0xc0009b34c8, 0x197, 0xc00000f180, 0xc8e1a0, 0xc000113e50, 0x0)
,	/usr/local/go/src/encoding/gob/decode.go:630 +0x227
,encoding/gob.(*Decoder).decOpFor.func3(0xc00014e678, 0xc00000e680, 0xa77e80, 0xc0009b34c8, 0x197)
,	/usr/local/go/src/encoding/gob/decode.go:848 +0x78
,encoding/gob.(*Decoder).decodeStruct(0xc0001aa380, 0xc00000ef60, 0xb79b60, 0xc0009b3440, 0x199)
,	/usr/local/go/src/encoding/gob/decode.go:471 +0xe2
,encoding/gob.(*Decoder).decOpFor.func4(0xc00007d600, 0xc00000e660, 0xb79b60, 0xc0009b3440, 0x199)
,	/usr/local/go/src/encoding/gob/decode.go:860 +0x54
,encoding/gob.(*Decoder).decodeArrayHelper(0xc0001aa380, 0xc00000e660, 0xaa1c20, 0xc000344400, 0x197, 0xc00000f2c0, 0x1383, 0xc8e1a0, 0xc000208120, 0x0)
,	/usr/local/go/src/encoding/gob/decode.go:530 +0x17b
,encoding/gob.(*Decoder).decodeSlice(0xc0001aa380, 0xc00000e660, 0xaa1c20, 0xc000344400, 0x197, 0xc00000f2c0, 0xc8e1a0, 0xc000208120, 0x0)
,	/usr/local/go/src/encoding/gob/decode.go:630 +0x227
,encoding/gob.(*Decoder).decOpFor.func3(0xc0000d2458, 0xc00000e660, 0xaa1c20, 0xc000344400, 0x197)
,	/usr/local/go/src/encoding/gob/decode.go:848 +0x78
,encoding/gob.(*Decoder).decodeStruct(0xc0001aa380, 0xc00000ef20, 0xb2af60, 0xc0003443d8, 0x199)
,	/usr/local/go/src/encoding/gob/decode.go:471 +0xe2
,encoding/gob.(*Decoder).decodeValue(0xc0001aa380, 0xc000000043, 0xae7f40, 0xc0003443d8, 0x16)
,	/usr/local/go/src/encoding/gob/decode.go:1205 +0x2bc
,encoding/gob.(*Decoder).DecodeValue(0xc0001aa380, 0xae7f40, 0xc0003443d8, 0x16, 0x0, 0x0)
,	/usr/local/go/src/encoding/gob/decoder.go:213 +0x148
,encoding/gob.(*Decoder).Decode(0xc0001aa380, 0xae7f40, 0xc0003443d8, 0x2308b8, 0x230ab8)
,	/usr/local/go/src/encoding/gob/decoder.go:188 +0x16d
,nordvpn/daemon.(*ServersData).load(0xc0003443d8, 0x0, 0x0)
,	/builds/nordvpn/apps-source/linux-app/src/daemon/data_models.go:165 +0xed
,nordvpn/daemon.(*DataManager).LoadData(0xc000344340)
,	/builds/nordvpn/apps-source/linux-app/src/daemon/data_manager.go:40 +0x9e
,created by main.main
,	/builds/nordvpn/apps-source/linux-app/src/cmd/daemon/main.go:146 +0xa1e
,
,goroutine 26 [semacquire]:
,sync.runtime_SemacquireMutex(0xc0003444c4, 0x0, 0x1)
,	/usr/local/go/src/runtime/sema.go:71 +0x47
,sync.(*Mutex).lockSlow(0xc0003444c0)
,	/usr/local/go/src/sync/mutex.go:138 +0xfc
,sync.(*Mutex).Lock(...)
,	/usr/local/go/src/sync/mutex.go:81
,nordvpn/daemon.(*DataManager).CountryDataExists(0xc000344340, 0xc00049e000)
,	/builds/nordvpn/apps-source/linux-app/src/daemon/data_manager.go:68 +0xb5
,nordvpn/daemon.JobCountries.func1(0x0, 0x0)
,	/builds/nordvpn/apps-source/linux-app/src/daemon/job_countries.go:10 +0x4d
,reflect.Value.call(0xa7e460, 0xc000498000, 0x13, 0xb8e68a, 0x4, 0x11721e8, 0x0, 0x0, 0xc0004bde18, 0x44db7c, ...)
,	/usr/local/go/src/reflect/value.go:460 +0x8ab
,reflect.Value.Call(0xa7e460, 0xc000498000, 0x13, 0x11721e8, 0x0, 0x0, 0x4c6126, 0x4c5850, 0xc77cb4)
,	/usr/local/go/src/reflect/value.go:321 +0xb4
,github.com/jasonlvhit/gocron.(*Job).run(0xc000496000, 0x0, 0x0, 0x0, 0x0, 0x0)
,	/go/pkg/mod/github.com/jasonlvhit/gocron@v0.0.0-20190729230047-f0655e5d3ade/gocron.go:123 +0x3d4
,github.com/jasonlvhit/gocron.(*Scheduler).RunAllwithDelay(0xc000480000, 0x0)
,	/go/pkg/mod/github.com/jasonlvhit/gocron@v0.0.0-20190729230047-f0655e5d3ade/gocron.go:443 +0x5e
,github.com/jasonlvhit/gocron.(*Scheduler).RunAll(...)
,	/go/pkg/mod/github.com/jasonlvhit/gocron@v0.0.0-20190729230047-f0655e5d3ade/gocron.go:437
,nordvpn/daemon.(*Rpc).StartJobs(0xc00012b3b0, 0xca0320)
,	/builds/nordvpn/apps-source/linux-app/src/daemon/rpc.go:70 +0x661
,created by main.main
,	/builds/nordvpn/apps-source/linux-app/src/cmd/daemon/main.go:147 +0xa43
,
,goroutine 31 [syscall]:
,os/signal.signal_recv(0x0)
,	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
,os/signal.loop()
,	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
,created by os/signal.Notify.func1
,	/usr/local/go/src/os/signal/signal.go:127 +0x44
,
,goroutine 13 [select]:
,github.com/jasonlvhit/gocron.(*Scheduler).Start.func1(0xc0000a0320, 0xc000366000, 0xc00007a000)
,	/go/pkg/mod/github.com/jasonlvhit/gocron@v0.0.0-20190729230047-f0655e5d3ade/gocron.go:499 +0xb6
,created by github.com/jasonlvhit/gocron.(*Scheduler).Start
,	/go/pkg/mod/github.com/jasonlvhit/gocron@v0.0.0-20190729230047-f0655e5d3ade/gocron.go:497 +0x87
,
-
  
Whoops! Cannot reach System Daemon.
,connection error: desc = "transport: Error while dialing dial unix /run/nordvpnd.sock: connect: connection refused"
,connection error: desc = "transport: Error while dialing dial unix /run/nordvpnd.sock: connect: connection refused"
,
-
  
Whoops! Cannot reach System Daemon.```

**Comment by bubuntux** [comment]
seems to be an issue with you docker installation, not with this image
