### ISSUE TITLE
Issues with network when VPN container reboot

### ISSUE THREAD

**Issue by IH3lios** [bubuntux/nordvpn#64]
Hi, I recently started having issues with my VPN container, where it would cash/restart and make every other container dependant on it no longer accessible, even with a successful reboot. The only fix to get everything working again is to drop everything with docker-compose down and bring them back up with docker-compose up.

A few tests that I had done, was checking all dependant containers network id's and all they all match the VPN container id, so I don't think that's an issue. The primary issue is when I reboot the VPN container, NOT kill it, everything else is no longer accessible even if the VPN container goes back up successfully.

My similar example setup:

`version: "3"
services:
  vpn:
    image: bubuntux/nordvpn
    network_mode: bridge
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=user@email.com
      - PASS='pas$word'
      - CONNECT=United_States
      - TECHNOLOGY=OpenVPN
      - PROTOCOL=UDP
      - OBFUSCATE=Enable
      - TZ=America/New_York
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    depends_on:
      - vpn
    restart: unless-stopped
    network_mode: service:vpn
    volumes:
      - data:/config
      - downloads:/downloads
      - watch:/watch
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/New_York
    restart: unless-stopped`

NordVPN container crashes with the following error (not consistently, happens once in a while).

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x946bf3]

goroutine 725 [running]:
nordvpn/daemon.Connect(0xc00090e540, 0xbf0260, 0xc000116480, 0xc0000b2140, 0xc000098b60, 0x1583ae6, 0xc000503180, 0x18, 0xc0005031c0, 0x18, ...)
        /builds/nordvpn/apps-source/linux-app/src/daemon/rpc.go:226 +0x2f3
created by nordvpn/daemon.(*Rpc).Connect
        /builds/nordvpn/apps-source/linux-app/src/daemon/rpc_connect.go:131 +0x822

This has never happened to me before until recently when I pulled to the latest image.

**Comment by IH3lios** [comment]
Seems like the issue was with a specific server on nords side.
